### ISSUE TITLE
HDD Light - not working.

### ISSUE THREAD

**Issue by victordk** [sipeed/NanoKVM#136]
Hi 

Do anybody have the HDD activity light working on the web interface?

I run the full version updated with 2.10 firmware and KVM-A passthrough with the HDD light working on the PC case.

**Comment by Z2Z-GuGu** [comment]
Thanks for your question. Due to the limited number of ATX wire cores, only PWR_LED, PWR_SW, and RST_SW signals can be processed in NanoKVM, and the status of HDD LED cannot be received by NanoKVM.And I found that there are missing parts in the description on the wiki, and I will supplement them as soon as possible. Thank you again.

**Comment by stuartm** [comment]
The answer doesn't explain why, if HDD Activity LED cannot be received there is an icon for it in the GUI labelled "HDD LED"? Shouldn't this be removed from the UI if it cannot show anything?

**Comment by stuartm** [comment]
> Shouldn't this be removed from the UI if it cannot show anything?

My bad, I see this has already been removed in the latest firmware.
