### ISSUE TITLE
USB keyboard/mouse problem: Computer hangs on boot with keyboard plugged in

### ISSUE THREAD

**Issue by mchugh19** [sipeed/NanoKVM#38]
When booting (image version 1.2.0, app version 2.0.6) on an Intel Desktop Board DQ77MK with the KVM connected via the keyboard/mouse usb cable, the computer doesn't boot. The monitor shows the initial splash screen with the prompt to press keys to boot to bios settings, but hangs at that screen. No amount of keyboard input allows booting. 

If the device is rebooted without the keyboard/mouse cable connected, all is fine and it proceeds.

**Comment by wj-xiao** [comment]
We have fix it in version 2.0.7. Please update.

**Comment by wj-xiao** [comment]
It seems the remote host is booting from the NanoKVM virtual USB disk instead of the system boot disk. This might be related to the default setting of the motherboard. 

You could try disabling the NanoKVM virtual USB disk first, then reboot the remote host to see if it works properly.

![CleanShot 2024-09-11 at 11 31 58](https://github.com/user-attachments/assets/1ee18f63-0f55-4148-8025-3ef00424ec23)

**Comment by mchugh19** [comment]
Yep, that did it! Thanks for the suggestion!
